CREATE TABLE IF NOT EXISTS comments (
  id SERIAL PRIMARY KEY,
  bench_id INTEGER NOT NULL,
  author_name VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  parent_comment_id INTEGER NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
